const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("vrChat", {
  getConfig: () => ipcRenderer.invoke("config:get"),
  getAppVersion: () => ipcRenderer.invoke("app:version"),
  getStatuses: () => ipcRenderer.invoke("status:get"),
  saveConfig: (config) => ipcRenderer.invoke("config:save", config),
  checkForUpdates: () => ipcRenderer.invoke("updates:check"),
  getAuthStatus: (platform) => ipcRenderer.invoke("auth:status", platform),
  signInToService: (platform) => ipcRenderer.invoke("auth:sign-in", platform),
  signOutService: (platform) => ipcRenderer.invoke("auth:logout", platform),
  getYouTubeCookieStatus: () => ipcRenderer.invoke("youtube:cookie-status"),
  signInToYouTube: () => ipcRenderer.invoke("youtube:sign-in"),
  startOAuthLogin: (platform) => ipcRenderer.invoke("oauth:login", platform),
  logoutOAuth: (platform) => ipcRenderer.invoke("oauth:logout", platform),
  testAlert: (alert) => ipcRenderer.invoke("alerts:test", alert),
  getAlertUrl: () => ipcRenderer.invoke("alerts:url"),
  getPrimaryAlertSource: () => ipcRenderer.invoke("alerts:primary"),
  connectObs: () => ipcRenderer.invoke("obs:connect"),
  disconnectObs: () => ipcRenderer.invoke("obs:disconnect"),
  runObsAction: (action) => ipcRenderer.invoke("obs:action", action),
  getProviderState: () => ipcRenderer.invoke("provider:state"),
  setProviderScene: (sceneName) => ipcRenderer.invoke("provider:set-scene", sceneName),
  toggleProviderAudio: (inputName) => ipcRenderer.invoke("provider:toggle-audio", inputName),
  runModerationAction: (action, target) => ipcRenderer.invoke("moderation:action", action, target),
  toggleOpenVrOverlay: () => ipcRenderer.invoke("openvr:toggle"),
  setClickThrough: (enabled) => ipcRenderer.invoke("overlay:set-click-through", enabled),
  toggleClickThrough: () => ipcRenderer.invoke("overlay:toggle-click-through"),
  setAlwaysOnTop: (enabled) => ipcRenderer.invoke("overlay:set-always-on-top", enabled),
  openExternal: (url) => ipcRenderer.invoke("overlay:open-external", url),
  minimize: () => ipcRenderer.invoke("window:minimize"),
  close: () => ipcRenderer.invoke("window:close"),
  onMessage: (callback) => ipcRenderer.on("chat:message", (_event, value) => callback(value)),
  onAlert: (callback) => ipcRenderer.on("suite:alert", (_event, value) => callback(value)),
  onStatus: (callback) => ipcRenderer.on("chat:status", (_event, value) => callback(value)),
  onReset: (callback) => ipcRenderer.on("chat:reset", callback),
  onConfigUpdated: (callback) => ipcRenderer.on("config:updated", (_event, value) => callback(value)),
  onClickThrough: (callback) => ipcRenderer.on("overlay:click-through", (_event, value) => callback(value))
});
